package com.masterquentus.hexcraft;

import com.masterquentus.hexcraft.block.HexcraftBlocks;
import com.masterquentus.hexcraft.block.entity.HexcraftBlockEntities;
import com.masterquentus.hexcraft.block.entity.HexcraftWoodTypes;
import com.masterquentus.hexcraft.item.HexcraftCreativeModTabs;
import com.masterquentus.hexcraft.item.HexcraftItems;
import com.masterquentus.hexcraft.loot.modifier.HexcraftLootModifiers;
import com.masterquentus.hexcraft.world.HexcraftMenus;
import com.mojang.logging.LogUtils;
import net.minecraft.client.renderer.Sheets;
import net.minecraft.client.renderer.blockentity.BlockEntityRenderers;
import net.minecraft.client.renderer.blockentity.SignRenderer;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.FlowerPotBlock;
import net.minecraft.world.level.block.state.properties.WoodType;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.event.CreativeModeTabEvent;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import org.slf4j.Logger;

@Mod(Hexcraft.MOD_ID)
public class Hexcraft {
    public static final String MOD_ID = "hexcraft";
    private static final Logger LOGGER = LogUtils.getLogger();


    public Hexcraft() {
        IEventBus modEventBus = FMLJavaModLoadingContext.get().getModEventBus();

        HexcraftItems.register(modEventBus);
        HexcraftBlocks.register(modEventBus);
        HexcraftBlockEntities.register(modEventBus);
        HexcraftLootModifiers.register(modEventBus);
        HexcraftMenus.register(modEventBus);

        modEventBus.addListener(this::commonSetup);
        MinecraftForge.EVENT_BUS.register(this);

        modEventBus.addListener(this::addCreative);
    }

    private void commonSetup(final FMLCommonSetupEvent event) {

        BlockEntityRenderers.register(HexcraftBlockEntities.SIGN_BLOCK_ENTITIES.get(), SignRenderer::new);
        WoodType.register(HexcraftWoodTypes.EBONY);
        WoodType.register(HexcraftWoodTypes.BLOOD_OAK);
        WoodType.register(HexcraftWoodTypes.HELL_BARK);
        WoodType.register(HexcraftWoodTypes.WHITE_OAK);
        WoodType.register(HexcraftWoodTypes.ALDER);
        WoodType.register(HexcraftWoodTypes.WITCH_HAZEL);
        WoodType.register(HexcraftWoodTypes.WILLOW);
        WoodType.register(HexcraftWoodTypes.HAWTHORN);
        WoodType.register(HexcraftWoodTypes.CEDAR);
        WoodType.register(HexcraftWoodTypes.DISTORTED);
        WoodType.register(HexcraftWoodTypes.ELDER);
        WoodType.register(HexcraftWoodTypes.JUNIPER);
        WoodType.register(HexcraftWoodTypes.ROWAN);
        WoodType.register(HexcraftWoodTypes.TWISTED);
        WoodType.register(HexcraftWoodTypes.WITCH_WOOD);
        WoodType.register(HexcraftWoodTypes.ECHO_WOOD);

    }

    private void addCreative(CreativeModeTabEvent.BuildContents event) {
    if(event.getTab() == CreativeModeTabs.INGREDIENTS) {
        event.accept(HexcraftItems.INFUSED_FABRIC);
        event.accept(HexcraftItems.LILITH_CONTRACT);
        event.accept(HexcraftItems.LILITH_SOUL);
        event.accept(HexcraftItems.MAGIC_CRYSTAL);
        event.accept(HexcraftItems.FAIRY_DUST);
        event.accept(HexcraftItems.PIXIE_DUST);
        event.accept(HexcraftItems.BLANK_RUNE);
        event.accept(HexcraftItems.AIR_RUNE);
        event.accept(HexcraftItems.EARTH_RUNE);
        event.accept(HexcraftItems.FIRE_RUNE);
        event.accept(HexcraftItems.WATER_RUNE);
        event.accept(HexcraftItems.RED_RUNE);
        event.accept(HexcraftItems.BLACK_RUNE);
        event.accept(HexcraftItems.BLUE_RUNE);
        event.accept(HexcraftItems.GREEN_RUNE);
        event.accept(HexcraftItems.ORANGE_RUNE);
        event.accept(HexcraftItems.PURPLE_RUNE);
        event.accept(HexcraftItems.WHITE_RUNE);
        event.accept(HexcraftItems.YELLOW_RUNE);
        event.accept(HexcraftItems.ROPE);
        event.accept(HexcraftItems.MOONSTONE);
        event.accept(HexcraftItems.RAW_SILVER);
        event.accept(HexcraftItems.SILVER_INGOT);
        event.accept(HexcraftItems.SILVER_NUGGET);
        event.accept(HexcraftItems.VAMPIRIC_GEM);
        event.accept(HexcraftItems.WHITE_OAK_ASH);
        event.accept(HexcraftItems.WHITE_OAK_ASH_DAGGER);
        event.accept(HexcraftItems.LIVING_KELP_ITEM);
        event.accept(HexcraftItems.MANDRAKE_SEEDS);
        event.accept(HexcraftItems.MANDRAKE_ROOT);
        event.accept(HexcraftItems.GARLIC);
        event.accept(HexcraftItems.VERVAIN_SEEDS);
        event.accept(HexcraftItems.VERVAIN);
        event.accept(HexcraftItems.WOLFSBANE_SEEDS);
        event.accept(HexcraftItems.WOLFSBANE);
        event.accept(HexcraftItems.IRENIAL_SEEDS);
        event.accept(HexcraftItems.IRENIAL);
        event.accept(HexcraftItems.MIRA_SEEDS);
        event.accept(HexcraftItems.MIRA);
        event.accept(HexcraftItems.XERIFAE_SEEDS);
        event.accept(HexcraftItems.XERIFAE);
        event.accept(HexcraftItems.SENIA_SEEDS);
        event.accept(HexcraftItems.SENIA);
        event.accept(HexcraftItems.AERPINE_SEEDS);
        event.accept(HexcraftItems.AERPINE);
        event.accept(HexcraftItems.PERENNIA_SEEDS);
        event.accept(HexcraftItems.PERENNIA);
        event.accept(HexcraftItems.BELLADONNA_SEEDS);
        event.accept(HexcraftItems.BELLADONNA);
        event.accept(HexcraftItems.HELLEBORE_SEEDS);
        event.accept(HexcraftItems.HELLEBORE);
        event.accept(HexcraftItems.SAGE_SEEDS);
        event.accept(HexcraftItems.SAGE);
        event.accept(HexcraftItems.WORMWOOD_SEEDS);
        event.accept(HexcraftItems.WORMWOOD);
        event.accept(HexcraftItems.WATER_ARTICHOKE_SEEDS);
        event.accept(HexcraftItems.WATER_ARTICHOKE);
        event.accept(HexcraftItems.CINDER_BERRY);

    }

        if(event.getTab() == CreativeModeTabs.NATURAL_BLOCKS) {
            event.accept(HexcraftBlocks.BLACK_OBSIDIAN);
            event.accept(HexcraftBlocks.TAINTED_MAGIC_BLOCK);
            event.accept(HexcraftBlocks.TAINTED_MAGIC_VEIN);
            event.accept(HexcraftBlocks.PIXIE_HOUSE);
            event.accept(HexcraftBlocks.CURSED_SOIL);
            event.accept(HexcraftBlocks.MOONSTONE_ORE);
            event.accept(HexcraftBlocks.END_MOONSTONE_ORE);
            event.accept(HexcraftBlocks.NETHER_MOONSTONE_ORE);
            event.accept(HexcraftBlocks.DEEPSLATE_MOONSTONE_ORE);
            event.accept(HexcraftBlocks.SILVER_ORE);
            event.accept(HexcraftBlocks.END_SILVER_ORE);
            event.accept(HexcraftBlocks.NETHER_SILVER_ORE);
            event.accept(HexcraftBlocks.DEEPSLATE_SILVER_ORE);
            event.accept(HexcraftBlocks.VAMPIRIC_ORE);
            event.accept(HexcraftBlocks.END_VAMPIRIC_ORE);
            event.accept(HexcraftBlocks.NETHER_VAMPIRIC_ORE);
            event.accept(HexcraftBlocks.DEEPSLATE_VAMPIRIC_ORE);
            event.accept(HexcraftBlocks.PEARL_STONE);
            event.accept(HexcraftBlocks.CRIMSON_STONE);
            event.accept(HexcraftBlocks.UNDER_WORLD_STONE);
            event.accept(HexcraftBlocks.CRIMSON_SAND);
            event.accept(HexcraftBlocks.FAIRY_SAND);
            event.accept(HexcraftBlocks.PIXIE_SAND);
            event.accept(HexcraftBlocks.CRIMSON_ICE);
            event.accept(HexcraftBlocks.CRIMSON_PACKED_ICE);
            event.accept(HexcraftBlocks.CRIMSON_MAGMA);
            event.accept(HexcraftBlocks.MAGIC_CRYSTAL_BLOCK);
            event.accept(HexcraftBlocks.BUDDING_MAGIC_CRYSTAL);
            event.accept(HexcraftBlocks.MAGIC_CRYSTAL_CLUSTER);
            event.accept(HexcraftBlocks.LARGE_MAGIC_CRYSTAL_BUD);
            event.accept(HexcraftBlocks.MEDIUM_MAGIC_CRYSTAL_BUD);
            event.accept(HexcraftBlocks.SMALL_MAGIC_CRYSTAL_BUD);
            event.accept(HexcraftBlocks.EBONY_LOG);
            event.accept(HexcraftBlocks.BLOOD_OAK_LOG);
            event.accept(HexcraftBlocks.HELL_BARK_LOG);
            event.accept(HexcraftBlocks.WHITE_OAK_LOG);
            event.accept(HexcraftBlocks.ALDER_LOG);
            event.accept(HexcraftBlocks.WITCH_HAZEL_LOG);
            event.accept(HexcraftBlocks.WILLOW_LOG);
            event.accept(HexcraftBlocks.HAWTHORN_LOG);
            event.accept(HexcraftBlocks.CEDAR_LOG);
            event.accept(HexcraftBlocks.DISTORTED_LOG);
            event.accept(HexcraftBlocks.ELDER_LOG);
            event.accept(HexcraftBlocks.JUNIPER_LOG);
            event.accept(HexcraftBlocks.ROWAN_LOG);
            event.accept(HexcraftBlocks.TWISTED_LOG);
            event.accept(HexcraftBlocks.WITCH_WOOD_LOG);
            event.accept(HexcraftBlocks.ECHO_WOOD_LOG);
            event.accept(HexcraftBlocks.EBONY_LEAVES);
            event.accept(HexcraftBlocks.EBONY_LEAVES_PILE);
            event.accept(HexcraftBlocks.BLOOD_OAK_LEAVES);
            event.accept(HexcraftBlocks.BLOOD_OAK_LEAVES_PILE);
            event.accept(HexcraftBlocks.HELL_BARK_LEAVES);
            event.accept(HexcraftBlocks.HELL_BARK_LEAVES_PILE);
            event.accept(HexcraftBlocks.WHITE_OAK_LEAVES);
            event.accept(HexcraftBlocks.WHITE_OAK_LEAVES_PILE);
            event.accept(HexcraftBlocks.ALDER_LEAVES);
            event.accept(HexcraftBlocks.ALDER_LEAVES_PILE);
            event.accept(HexcraftBlocks.WITCH_HAZEL_LEAVES);
            event.accept(HexcraftBlocks.WITCH_HAZEL_LEAVES_PILE);
            event.accept(HexcraftBlocks.WILLOW_LEAVES);
            event.accept(HexcraftBlocks.WILLOW_LEAVES_PILE);
            event.accept(HexcraftBlocks.HAWTHORN_LEAVES);
            event.accept(HexcraftBlocks.HAWTHORN_LEAVES_PILE);
            event.accept(HexcraftBlocks.CEDAR_LEAVES);
            event.accept(HexcraftBlocks.CEDAR_LEAVES_PILE);
            event.accept(HexcraftBlocks.DISTORTED_LEAVES);
            event.accept(HexcraftBlocks.DISTORTED_LEAVES_PILE);
            event.accept(HexcraftBlocks.ELDER_LEAVES);
            event.accept(HexcraftBlocks.ELDER_LEAVES_PILE);
            event.accept(HexcraftBlocks.JUNIPER_LEAVES);
            event.accept(HexcraftBlocks.JUNIPER_LEAVES_PILE);
            event.accept(HexcraftBlocks.ROWAN_LEAVES);
            event.accept(HexcraftBlocks.ROWAN_LEAVES_PILE);
            event.accept(HexcraftBlocks.TWISTED_LEAVES);
            event.accept(HexcraftBlocks.TWISTED_LEAVES_PILE);
            event.accept(HexcraftBlocks.WITCH_WOOD_LEAVES);
            event.accept(HexcraftBlocks.WITCH_WOOD_LEAVES_PILE);
            event.accept(HexcraftBlocks.ECHO_WOOD_LEAVES);
            event.accept(HexcraftBlocks.ECHO_WOOD_LEAVES_PILE);
            event.accept(HexcraftBlocks.ECHO_FUNGAL_LAMP);
            event.accept(HexcraftBlocks.HELL_FUNGAL_LAMP);
            event.accept(HexcraftBlocks.BLOODY_ROSE);
            event.accept(HexcraftBlocks.VAMPIRE_ORCHID);
            event.accept(HexcraftBlocks.WILD_BRAMBLE);
            event.accept(HexcraftBlocks.ENDER_BRAMBLE);
            event.accept(HexcraftBlocks.BLOOD_MUSHROOM_BLOCK);
            event.accept(HexcraftBlocks.BLOOD_MUSHROOM_STEM);


        }

        if(event.getTab() == CreativeModeTabs.BUILDING_BLOCKS) {
            event.accept(HexcraftBlocks.MOONSTONE_BLOCK);
            event.accept(HexcraftBlocks.SILVER_BLOCK);
            event.accept(HexcraftBlocks.VAMPIRIC_BLOCK);
            event.accept(HexcraftBlocks.PEARL_COBBLESTONE);
            event.accept(HexcraftBlocks.PEARL_STONE_BRICKS);
            event.accept(HexcraftBlocks.POLISHED_PEARL_STONE);
            event.accept(HexcraftBlocks.CHISELED_PEARL_STONE);
            event.accept(HexcraftBlocks.CRACKED_PEARL_STONE);
            event.accept(HexcraftBlocks.CRIMSON_COBBLESTONE);
            event.accept(HexcraftBlocks.CRIMSON_STONE_BRICKS);
            event.accept(HexcraftBlocks.POLISHED_CRIMSON_STONE);
            event.accept(HexcraftBlocks.CHISELED_CRIMSON_STONE);
            event.accept(HexcraftBlocks.CRACKED_CRIMSON_STONE);
            event.accept(HexcraftBlocks.UNDER_WORLD_COBBLESTONE);
            event.accept(HexcraftBlocks.UNDER_WORLD_STONE_BRICKS);
            event.accept(HexcraftBlocks.POLISHED_UNDER_WORLD_STONE);
            event.accept(HexcraftBlocks.CHISELED_UNDER_WORLD_STONE);
            event.accept(HexcraftBlocks.CRACKED_UNDER_WORLD_STONE);
            event.accept(HexcraftBlocks.CRIMSON_SAND_STONE);
            event.accept(HexcraftBlocks.SMOOTH_CRIMSON_SAND_STONE);
            event.accept(HexcraftBlocks.CHISELED_CRIMSON_SAND_STONE);
            event.accept(HexcraftBlocks.CUT_CRIMSON_SAND_STONE);
            event.accept(HexcraftBlocks.CRIMSON_GLASS);
            event.accept(HexcraftBlocks.CRIMSON_GLASS_PANE);
            event.accept(HexcraftBlocks.FAIRY_SAND_STONE);
            event.accept(HexcraftBlocks.SMOOTH_FAIRY_SAND_STONE);
            event.accept(HexcraftBlocks.CHISELED_FAIRY_SAND_STONE);
            event.accept(HexcraftBlocks.CUT_FAIRY_SAND_STONE);
            event.accept(HexcraftBlocks.FAIRY_GLASS);
            event.accept(HexcraftBlocks.FAIRY_GLASS_PANE);
            event.accept(HexcraftBlocks.PIXIE_SAND_STONE);
            event.accept(HexcraftBlocks.SMOOTH_PIXIE_SAND_STONE);
            event.accept(HexcraftBlocks.CHISELED_PIXIE_SAND_STONE);
            event.accept(HexcraftBlocks.CUT_PIXIE_SAND_STONE);
            event.accept(HexcraftBlocks.PIXIE_GLASS);
            event.accept(HexcraftBlocks.PIXIE_GLASS_PANE);
            event.accept(HexcraftBlocks.EBONY_WOOD);
            event.accept(HexcraftBlocks.BLOOD_OAK_WOOD);
            event.accept(HexcraftBlocks.HELL_BARK_WOOD);
            event.accept(HexcraftBlocks.WHITE_OAK_WOOD);
            event.accept(HexcraftBlocks.ALDER_WOOD);
            event.accept(HexcraftBlocks.WITCH_HAZEL_WOOD);
            event.accept(HexcraftBlocks.WILLOW_WOOD);
            event.accept(HexcraftBlocks.HAWTHORN_WOOD);
            event.accept(HexcraftBlocks.CEDAR_WOOD);
            event.accept(HexcraftBlocks.DISTORTED_WOOD);
            event.accept(HexcraftBlocks.ELDER_LOG);
            event.accept(HexcraftBlocks.JUNIPER_WOOD);
            event.accept(HexcraftBlocks.ROWAN_WOOD);
            event.accept(HexcraftBlocks.TWISTED_WOOD);
            event.accept(HexcraftBlocks.WITCH_WOOD_WOOD);
            event.accept(HexcraftBlocks.ECHO_WOOD_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_EBONY_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_BLOOD_OAK_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_HELL_BARK_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_WHITE_OAK_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_ALDER_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_WITCH_HAZEL_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_WILLOW_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_HAWTHORN_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_CEDAR_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_DISTORTED_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_ELDER_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_JUNIPER_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_ROWAN_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_TWISTED_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_WITCH_WOOD_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_ECHO_WOOD_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_EBONY_LOG);
            event.accept(HexcraftBlocks.STRIPPED_BLOOD_OAK_LOG);
            event.accept(HexcraftBlocks.STRIPPED_HELL_BARK_LOG);
            event.accept(HexcraftBlocks.STRIPPED_WHITE_OAK_LOG);
            event.accept(HexcraftBlocks.STRIPPED_ALDER_LOG);
            event.accept(HexcraftBlocks.STRIPPED_WITCH_HAZEL_LOG);
            event.accept(HexcraftBlocks.STRIPPED_WILLOW_LOG);
            event.accept(HexcraftBlocks.STRIPPED_HAWTHORN_LOG);
            event.accept(HexcraftBlocks.STRIPPED_CEDAR_LOG);
            event.accept(HexcraftBlocks.STRIPPED_DISTORTED_LOG);
            event.accept(HexcraftBlocks.STRIPPED_ELDER_LOG);
            event.accept(HexcraftBlocks.STRIPPED_JUNIPER_LOG);
            event.accept(HexcraftBlocks.STRIPPED_ROWAN_LOG);
            event.accept(HexcraftBlocks.STRIPPED_TWISTED_LOG);
            event.accept(HexcraftBlocks.STRIPPED_WITCH_WOOD_LOG);
            event.accept(HexcraftBlocks.STRIPPED_ECHO_WOOD_LOG);
            event.accept(HexcraftItems.EBONY_SIGN);
            event.accept(HexcraftItems.BLOOD_OAK_SIGN);
            event.accept(HexcraftItems.HELL_BARK_SIGN);
            event.accept(HexcraftItems.WHITE_OAK_SIGN);
            event.accept(HexcraftItems.ALDER_SIGN);
            event.accept(HexcraftItems.WITCH_HAZEL_SIGN);
            event.accept(HexcraftItems.WILLOW_SIGN);
            event.accept(HexcraftItems.HAWTHORN_SIGN);
            event.accept(HexcraftItems.CEDAR_SIGN);
            event.accept(HexcraftItems.DISTORTED_SIGN);
            event.accept(HexcraftItems.ELDER_SIGN);
            event.accept(HexcraftItems.JUNIPER_SIGN);
            event.accept(HexcraftItems.ROWAN_SIGN);
            event.accept(HexcraftItems.TWISTED_SIGN);
            event.accept(HexcraftItems.WITCH_WOOD_SIGN);
            event.accept(HexcraftItems.ECHO_WOOD_SIGN);
            event.accept(HexcraftItems.CRATE_EBONY);
            event.accept(HexcraftItems.CRATE_BLOOD_OAK);
            event.accept(HexcraftItems.CRATE_HELLBARK);
            event.accept(HexcraftItems.CRATE_WHITE_OAK);
            event.accept(HexcraftItems.CRATE_ALDER);
            event.accept(HexcraftItems.CRATE_WITCH_HAZEL);
            event.accept(HexcraftItems.CRATE_WILLOW);
            event.accept(HexcraftItems.CRATE_HAWTHORN);
            event.accept(HexcraftItems.CRATE_CEDAR);
            event.accept(HexcraftItems.CRATE_DISTORTED);
            event.accept(HexcraftItems.CRATE_ELDER);
            event.accept(HexcraftItems.CRATE_JUNIPER);
            event.accept(HexcraftItems.CRATE_ROWAN);
            event.accept(HexcraftItems.CRATE_TWISTED);
            event.accept(HexcraftItems.CRATE_WITCH_WOOD);
            event.accept(HexcraftItems.CRATE_ECHO_WOOD);
            event.accept(HexcraftItems.CRATE_OAK);
            event.accept(HexcraftItems.CRATE_SPRUCE);
            event.accept(HexcraftItems.CRATE_BIRCH);
            event.accept(HexcraftItems.CRATE_JUNGLE);
            event.accept(HexcraftItems.CRATE_ACACIA);
            event.accept(HexcraftItems.CRATE_DARK_OAK);
            event.accept(HexcraftItems.CRATE_CRIMSON);
            event.accept(HexcraftItems.CRATE_WARPED);
            event.accept(HexcraftItems.CRATE_MANGROVE);
            event.accept(HexcraftBlocks.EBONY_PLANKS);
            event.accept(HexcraftBlocks.BLOOD_OAK_PLANKS);
            event.accept(HexcraftBlocks.HELL_BARK_PLANKS);
            event.accept(HexcraftBlocks.WHITE_OAK_PLANKS);
            event.accept(HexcraftBlocks.ALDER_PLANKS);
            event.accept(HexcraftBlocks.WITCH_HAZEL_PLANKS);
            event.accept(HexcraftBlocks.WILLOW_PLANKS);
            event.accept(HexcraftBlocks.HAWTHORN_PLANKS);
            event.accept(HexcraftBlocks.CEDAR_PLANKS);
            event.accept(HexcraftBlocks.DISTORTED_PLANKS);
            event.accept(HexcraftBlocks.ELDER_PLANKS);
            event.accept(HexcraftBlocks.JUNIPER_PLANKS);
            event.accept(HexcraftBlocks.ROWAN_PLANKS);
            event.accept(HexcraftBlocks.TWISTED_PLANKS);
            event.accept(HexcraftBlocks.WITCH_WOOD_PLANKS);
            event.accept(HexcraftBlocks.ECHO_WOOD_PLANKS);
            event.accept(HexcraftBlocks.EBONY_BOOKSHELF);
            event.accept(HexcraftBlocks.BLOOD_OAK_BOOKSHELF);
            event.accept(HexcraftBlocks.HELL_BARK_BOOKSHELF);
            event.accept(HexcraftBlocks.WHITE_OAK_BOOKSHELF);
            event.accept(HexcraftBlocks.ALDER_BOOKSHELF);
            event.accept(HexcraftBlocks.WITCH_HAZEL_BOOKSHELF);
            event.accept(HexcraftBlocks.WILLOW_BOOKSHELF);
            event.accept(HexcraftBlocks.HAWTHORN_BOOKSHELF);
            event.accept(HexcraftBlocks.CEDAR_BOOKSHELF);
            event.accept(HexcraftBlocks.DISTORTED_BOOKSHELF);
            event.accept(HexcraftBlocks.ELDER_BOOKSHELF);
            event.accept(HexcraftBlocks.JUNIPER_BOOKSHELF);
            event.accept(HexcraftBlocks.ROWAN_BOOKSHELF);
            event.accept(HexcraftBlocks.TWISTED_BOOKSHELF);
            event.accept(HexcraftBlocks.WITCH_WOOD_BOOKSHELF);
            event.accept(HexcraftBlocks.ECHO_WOOD_BOOKSHELF);
            event.accept(HexcraftBlocks.FAIRY_LANTERN);
            event.accept(HexcraftBlocks.PIXIE_LANTERN);
            event.accept(HexcraftBlocks.LIVING_KELP_BLOCK);
            event.accept(HexcraftBlocks.LILITH_TROPHY);



        }

        if(event.getTab() == CreativeModeTabs.FOOD_AND_DRINKS) {
            event.accept(HexcraftItems.BLOOD_BOTTLE);
            event.accept(HexcraftItems.LILITH_BLOOD_BOTTLE);
            event.accept(HexcraftItems.BLOOD_APPLE);
            event.accept(HexcraftItems.JUNIPER_BERRIES);

        }

        if(event.getTab() == CreativeModeTabs.FUNCTIONAL_BLOCKS) {
            event.accept(HexcraftBlocks.HUNTERS_TABLE);
            event.accept(HexcraftBlocks.POPPET_TABLE);
            event.accept(HexcraftBlocks.WITCHES_CAULDRON);
            event.accept(HexcraftBlocks.COFFIN);
            event.accept(HexcraftBlocks.AMETHYST_CHIMES);


        }

        if(event.getTab() == CreativeModeTabs.TOOLS_AND_UTILITIES) {
            event.accept(HexcraftItems.WITCHES_SATCHEL);
            event.accept(HexcraftItems.VAMPIRIC_STAFF);
            event.accept(HexcraftItems.POPPET);
            event.accept(HexcraftItems.DEATH_PROTECTION_POPPET);
            event.accept(HexcraftItems.FIRE_PROTECTION_POPPET);
            event.accept(HexcraftItems.WATER_PROTECTION_POPPET);
            event.accept(HexcraftItems.SILVER_SWORD);
            event.accept(HexcraftItems.SILVER_PICKAXE);
            event.accept(HexcraftItems.SILVER_SHOVEL);
            event.accept(HexcraftItems.SILVER_AXE);
            event.accept(HexcraftItems.SILVER_HOE);

        }

        if(event.getTab() == HexcraftCreativeModTabs.HEXCRAFT_TAB) {
            event.accept(HexcraftItems.INFUSED_FABRIC);
            event.accept(HexcraftItems.BLOOD_BOTTLE);
            event.accept(HexcraftItems.LILITH_BLOOD_BOTTLE);
            event.accept(HexcraftItems.LILITH_CONTRACT);
            event.accept(HexcraftItems.LILITH_SOUL);
            event.accept(HexcraftItems.MAGIC_CRYSTAL);
            event.accept(HexcraftItems.FAIRY_DUST);
            event.accept(HexcraftItems.PIXIE_DUST);
            event.accept(HexcraftItems.BLANK_RUNE);
            event.accept(HexcraftItems.AIR_RUNE);
            event.accept(HexcraftItems.EARTH_RUNE);
            event.accept(HexcraftItems.FIRE_RUNE);
            event.accept(HexcraftItems.WATER_RUNE);
            event.accept(HexcraftItems.RED_RUNE);
            event.accept(HexcraftItems.BLACK_RUNE);
            event.accept(HexcraftItems.BLUE_RUNE);
            event.accept(HexcraftItems.GREEN_RUNE);
            event.accept(HexcraftItems.ORANGE_RUNE);
            event.accept(HexcraftItems.PURPLE_RUNE);
            event.accept(HexcraftItems.WHITE_RUNE);
            event.accept(HexcraftItems.YELLOW_RUNE);
            event.accept(HexcraftItems.ROPE);
            event.accept(HexcraftItems.MOONSTONE);
            event.accept(HexcraftItems.RAW_SILVER);
            event.accept(HexcraftItems.SILVER_INGOT);
            event.accept(HexcraftItems.SILVER_NUGGET);
            event.accept(HexcraftItems.VAMPIRIC_GEM);
            event.accept(HexcraftItems.WHITE_OAK_ASH);
            event.accept(HexcraftItems.WITCHES_SATCHEL);
            event.accept(HexcraftItems.VAMPIRIC_STAFF);
            event.accept(HexcraftItems.WHITE_OAK_ASH_DAGGER);
            event.accept(HexcraftItems.POPPET);
            event.accept(HexcraftItems.DEATH_PROTECTION_POPPET);
            event.accept(HexcraftItems.FIRE_PROTECTION_POPPET);
            event.accept(HexcraftItems.WATER_PROTECTION_POPPET);
            event.accept(HexcraftItems.SILVER_SWORD);
            event.accept(HexcraftItems.SILVER_PICKAXE);
            event.accept(HexcraftItems.SILVER_SHOVEL);
            event.accept(HexcraftItems.SILVER_AXE);
            event.accept(HexcraftItems.SILVER_HOE);
            event.accept(HexcraftItems.BLOOD_APPLE);
            event.accept(HexcraftItems.JUNIPER_BERRIES);
            event.accept(HexcraftItems.WITCHES_LADDER_ITEM);
            event.accept(HexcraftItems.LIVING_KELP_ITEM);
            event.accept(HexcraftItems.MANDRAKE_SEEDS);
            event.accept(HexcraftItems.MANDRAKE_ROOT);
            event.accept(HexcraftItems.GARLIC);
            event.accept(HexcraftItems.VERVAIN_SEEDS);
            event.accept(HexcraftItems.VERVAIN);
            event.accept(HexcraftItems.WOLFSBANE_SEEDS);
            event.accept(HexcraftItems.WOLFSBANE);
            event.accept(HexcraftItems.IRENIAL_SEEDS);
            event.accept(HexcraftItems.IRENIAL);
            event.accept(HexcraftItems.MIRA_SEEDS);
            event.accept(HexcraftItems.MIRA);
            event.accept(HexcraftItems.XERIFAE_SEEDS);
            event.accept(HexcraftItems.XERIFAE);
            event.accept(HexcraftItems.SENIA_SEEDS);
            event.accept(HexcraftItems.SENIA);
            event.accept(HexcraftItems.AERPINE_SEEDS);
            event.accept(HexcraftItems.AERPINE);
            event.accept(HexcraftItems.PERENNIA_SEEDS);
            event.accept(HexcraftItems.PERENNIA);
            event.accept(HexcraftItems.BELLADONNA_SEEDS);
            event.accept(HexcraftItems.BELLADONNA);
            event.accept(HexcraftItems.HELLEBORE_SEEDS);
            event.accept(HexcraftItems.HELLEBORE);
            event.accept(HexcraftItems.SAGE_SEEDS);
            event.accept(HexcraftItems.SAGE);
            event.accept(HexcraftItems.WORMWOOD_SEEDS);
            event.accept(HexcraftItems.WORMWOOD);
            event.accept(HexcraftItems.WATER_ARTICHOKE_SEEDS);
            event.accept(HexcraftItems.WATER_ARTICHOKE);
            event.accept(HexcraftItems.CINDER_BERRY);
            event.accept(HexcraftBlocks.BLACK_OBSIDIAN);
            event.accept(HexcraftBlocks.HUNTERS_TABLE);
            event.accept(HexcraftBlocks.POPPET_TABLE);
            event.accept(HexcraftBlocks.FAIRY_HOUSE);
            event.accept(HexcraftBlocks.PIXIE_HOUSE);
            event.accept(HexcraftBlocks.WITCHES_CAULDRON);
            event.accept(HexcraftBlocks.COFFIN);
            event.accept(HexcraftBlocks.AMETHYST_CHIMES);
            event.accept(HexcraftBlocks.TAINTED_MAGIC_BLOCK);
            event.accept(HexcraftBlocks.TAINTED_MAGIC_VEIN);
            event.accept(HexcraftBlocks.CURSED_SOIL);
            event.accept(HexcraftBlocks.MOONSTONE_ORE);
            event.accept(HexcraftBlocks.END_MOONSTONE_ORE);
            event.accept(HexcraftBlocks.NETHER_MOONSTONE_ORE);
            event.accept(HexcraftBlocks.DEEPSLATE_MOONSTONE_ORE);
            event.accept(HexcraftBlocks.SILVER_ORE);
            event.accept(HexcraftBlocks.END_SILVER_ORE);
            event.accept(HexcraftBlocks.NETHER_SILVER_ORE);
            event.accept(HexcraftBlocks.DEEPSLATE_SILVER_ORE);
            event.accept(HexcraftBlocks.VAMPIRIC_ORE);
            event.accept(HexcraftBlocks.END_VAMPIRIC_ORE);
            event.accept(HexcraftBlocks.NETHER_VAMPIRIC_ORE);
            event.accept(HexcraftBlocks.DEEPSLATE_VAMPIRIC_ORE);
            event.accept(HexcraftBlocks.MOONSTONE_BLOCK);
            event.accept(HexcraftBlocks.SILVER_BLOCK);
            event.accept(HexcraftBlocks.PEARL_STONE);
            event.accept(HexcraftBlocks.PEARL_COBBLESTONE);
            event.accept(HexcraftBlocks.PEARL_STONE_BRICKS);
            event.accept(HexcraftBlocks.POLISHED_PEARL_STONE);
            event.accept(HexcraftBlocks.CHISELED_PEARL_STONE);
            event.accept(HexcraftBlocks.CRACKED_PEARL_STONE);
            event.accept(HexcraftBlocks.CRIMSON_STONE);
            event.accept(HexcraftBlocks.CRIMSON_COBBLESTONE);
            event.accept(HexcraftBlocks.CRIMSON_STONE_BRICKS);
            event.accept(HexcraftBlocks.POLISHED_CRIMSON_STONE);
            event.accept(HexcraftBlocks.CHISELED_CRIMSON_STONE);
            event.accept(HexcraftBlocks.CRACKED_CRIMSON_STONE);
            event.accept(HexcraftBlocks.UNDER_WORLD_STONE);
            event.accept(HexcraftBlocks.UNDER_WORLD_COBBLESTONE);
            event.accept(HexcraftBlocks.UNDER_WORLD_STONE_BRICKS);
            event.accept(HexcraftBlocks.POLISHED_UNDER_WORLD_STONE);
            event.accept(HexcraftBlocks.CHISELED_UNDER_WORLD_STONE);
            event.accept(HexcraftBlocks.CRACKED_UNDER_WORLD_STONE);
            event.accept(HexcraftBlocks.CRIMSON_SAND);
            event.accept(HexcraftBlocks.CRIMSON_SAND_STONE);
            event.accept(HexcraftBlocks.SMOOTH_CRIMSON_SAND_STONE);
            event.accept(HexcraftBlocks.CHISELED_CRIMSON_SAND_STONE);
            event.accept(HexcraftBlocks.CUT_CRIMSON_SAND_STONE);
            event.accept(HexcraftBlocks.CRIMSON_GLASS);
            event.accept(HexcraftBlocks.CRIMSON_GLASS_PANE);
            event.accept(HexcraftBlocks.FAIRY_SAND);
            event.accept(HexcraftBlocks.FAIRY_SAND_STONE);
            event.accept(HexcraftBlocks.SMOOTH_FAIRY_SAND_STONE);
            event.accept(HexcraftBlocks.CHISELED_FAIRY_SAND_STONE);
            event.accept(HexcraftBlocks.CUT_FAIRY_SAND_STONE);
            event.accept(HexcraftBlocks.FAIRY_GLASS);
            event.accept(HexcraftBlocks.FAIRY_GLASS_PANE);
            event.accept(HexcraftBlocks.PIXIE_SAND);
            event.accept(HexcraftBlocks.PIXIE_SAND_STONE);
            event.accept(HexcraftBlocks.SMOOTH_PIXIE_SAND_STONE);
            event.accept(HexcraftBlocks.CHISELED_PIXIE_SAND_STONE);
            event.accept(HexcraftBlocks.CUT_PIXIE_SAND_STONE);
            event.accept(HexcraftBlocks.PIXIE_GLASS);
            event.accept(HexcraftBlocks.PIXIE_GLASS_PANE);
            event.accept(HexcraftBlocks.CRIMSON_ICE);
            event.accept(HexcraftBlocks.CRIMSON_PACKED_ICE);
            event.accept(HexcraftBlocks.CRIMSON_MAGMA);
            event.accept(HexcraftBlocks.MAGIC_CRYSTAL_BLOCK);
            event.accept(HexcraftBlocks.BUDDING_MAGIC_CRYSTAL);
            event.accept(HexcraftBlocks.MAGIC_CRYSTAL_CLUSTER);
            event.accept(HexcraftBlocks.LARGE_MAGIC_CRYSTAL_BUD);
            event.accept(HexcraftBlocks.MEDIUM_MAGIC_CRYSTAL_BUD);
            event.accept(HexcraftBlocks.SMALL_MAGIC_CRYSTAL_BUD);
            event.accept(HexcraftBlocks.EBONY_WOOD);
            event.accept(HexcraftBlocks.BLOOD_OAK_WOOD);
            event.accept(HexcraftBlocks.HELL_BARK_WOOD);
            event.accept(HexcraftBlocks.WHITE_OAK_WOOD);
            event.accept(HexcraftBlocks.ALDER_WOOD);
            event.accept(HexcraftBlocks.WITCH_HAZEL_WOOD);
            event.accept(HexcraftBlocks.WILLOW_WOOD);
            event.accept(HexcraftBlocks.HAWTHORN_WOOD);
            event.accept(HexcraftBlocks.CEDAR_WOOD);
            event.accept(HexcraftBlocks.DISTORTED_WOOD);
            event.accept(HexcraftBlocks.ELDER_LOG);
            event.accept(HexcraftBlocks.JUNIPER_WOOD);
            event.accept(HexcraftBlocks.ROWAN_WOOD);
            event.accept(HexcraftBlocks.TWISTED_WOOD);
            event.accept(HexcraftBlocks.WITCH_WOOD_WOOD);
            event.accept(HexcraftBlocks.ECHO_WOOD_WOOD);
            event.accept(HexcraftBlocks.EBONY_LOG);
            event.accept(HexcraftBlocks.BLOOD_OAK_LOG);
            event.accept(HexcraftBlocks.HELL_BARK_LOG);
            event.accept(HexcraftBlocks.WHITE_OAK_LOG);
            event.accept(HexcraftBlocks.ALDER_LOG);
            event.accept(HexcraftBlocks.WITCH_HAZEL_LOG);
            event.accept(HexcraftBlocks.WILLOW_LOG);
            event.accept(HexcraftBlocks.HAWTHORN_LOG);
            event.accept(HexcraftBlocks.CEDAR_LOG);
            event.accept(HexcraftBlocks.DISTORTED_LOG);
            event.accept(HexcraftBlocks.ELDER_LOG);
            event.accept(HexcraftBlocks.JUNIPER_LOG);
            event.accept(HexcraftBlocks.ROWAN_LOG);
            event.accept(HexcraftBlocks.TWISTED_LOG);
            event.accept(HexcraftBlocks.WITCH_WOOD_LOG);
            event.accept(HexcraftBlocks.ECHO_WOOD_LOG);
            event.accept(HexcraftBlocks.STRIPPED_EBONY_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_BLOOD_OAK_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_HELL_BARK_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_WHITE_OAK_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_ALDER_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_WITCH_HAZEL_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_WILLOW_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_HAWTHORN_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_CEDAR_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_DISTORTED_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_ELDER_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_JUNIPER_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_ROWAN_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_TWISTED_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_WITCH_WOOD_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_ECHO_WOOD_WOOD);
            event.accept(HexcraftBlocks.STRIPPED_EBONY_LOG);
            event.accept(HexcraftBlocks.STRIPPED_BLOOD_OAK_LOG);
            event.accept(HexcraftBlocks.STRIPPED_HELL_BARK_LOG);
            event.accept(HexcraftBlocks.STRIPPED_WHITE_OAK_LOG);
            event.accept(HexcraftBlocks.STRIPPED_ALDER_LOG);
            event.accept(HexcraftBlocks.STRIPPED_WITCH_HAZEL_LOG);
            event.accept(HexcraftBlocks.STRIPPED_WILLOW_LOG);
            event.accept(HexcraftBlocks.STRIPPED_HAWTHORN_LOG);
            event.accept(HexcraftBlocks.STRIPPED_CEDAR_LOG);
            event.accept(HexcraftBlocks.STRIPPED_DISTORTED_LOG);
            event.accept(HexcraftBlocks.STRIPPED_ELDER_LOG);
            event.accept(HexcraftBlocks.STRIPPED_JUNIPER_LOG);
            event.accept(HexcraftBlocks.STRIPPED_ROWAN_LOG);
            event.accept(HexcraftBlocks.STRIPPED_TWISTED_LOG);
            event.accept(HexcraftBlocks.STRIPPED_WITCH_WOOD_LOG);
            event.accept(HexcraftBlocks.STRIPPED_ECHO_WOOD_LOG);
            event.accept(HexcraftBlocks.EBONY_LEAVES);
            event.accept(HexcraftBlocks.EBONY_LEAVES_PILE);
            event.accept(HexcraftBlocks.BLOOD_OAK_LEAVES);
            event.accept(HexcraftBlocks.BLOOD_OAK_LEAVES_PILE);
            event.accept(HexcraftBlocks.HELL_BARK_LEAVES);
            event.accept(HexcraftBlocks.HELL_BARK_LEAVES_PILE);
            event.accept(HexcraftBlocks.WHITE_OAK_LEAVES);
            event.accept(HexcraftBlocks.WHITE_OAK_LEAVES_PILE);
            event.accept(HexcraftBlocks.ALDER_LEAVES);
            event.accept(HexcraftBlocks.ALDER_LEAVES_PILE);
            event.accept(HexcraftBlocks.WITCH_HAZEL_LEAVES);
            event.accept(HexcraftBlocks.WITCH_HAZEL_LEAVES_PILE);
            event.accept(HexcraftBlocks.WILLOW_LEAVES);
            event.accept(HexcraftBlocks.WILLOW_LEAVES_PILE);
            event.accept(HexcraftBlocks.HAWTHORN_LEAVES);
            event.accept(HexcraftBlocks.HAWTHORN_LEAVES_PILE);
            event.accept(HexcraftBlocks.CEDAR_LEAVES);
            event.accept(HexcraftBlocks.CEDAR_LEAVES_PILE);
            event.accept(HexcraftBlocks.DISTORTED_LEAVES);
            event.accept(HexcraftBlocks.DISTORTED_LEAVES_PILE);
            event.accept(HexcraftBlocks.ELDER_LEAVES);
            event.accept(HexcraftBlocks.ELDER_LEAVES_PILE);
            event.accept(HexcraftBlocks.JUNIPER_LEAVES);
            event.accept(HexcraftBlocks.JUNIPER_LEAVES_PILE);
            event.accept(HexcraftBlocks.ROWAN_LEAVES);
            event.accept(HexcraftBlocks.ROWAN_LEAVES_PILE);
            event.accept(HexcraftBlocks.TWISTED_LEAVES);
            event.accept(HexcraftBlocks.TWISTED_LEAVES_PILE);
            event.accept(HexcraftBlocks.WITCH_WOOD_LEAVES);
            event.accept(HexcraftBlocks.WITCH_WOOD_LEAVES_PILE);
            event.accept(HexcraftBlocks.ECHO_WOOD_LEAVES);
            event.accept(HexcraftBlocks.ECHO_WOOD_LEAVES_PILE);
            event.accept(HexcraftBlocks.EBONY_PLANKS);
            event.accept(HexcraftBlocks.BLOOD_OAK_PLANKS);
            event.accept(HexcraftBlocks.HELL_BARK_PLANKS);
            event.accept(HexcraftBlocks.WHITE_OAK_PLANKS);
            event.accept(HexcraftBlocks.ALDER_PLANKS);
            event.accept(HexcraftBlocks.WITCH_HAZEL_PLANKS);
            event.accept(HexcraftBlocks.WILLOW_PLANKS);
            event.accept(HexcraftBlocks.HAWTHORN_PLANKS);
            event.accept(HexcraftBlocks.CEDAR_PLANKS);
            event.accept(HexcraftBlocks.DISTORTED_PLANKS);
            event.accept(HexcraftBlocks.ELDER_PLANKS);
            event.accept(HexcraftBlocks.JUNIPER_PLANKS);
            event.accept(HexcraftBlocks.ROWAN_PLANKS);
            event.accept(HexcraftBlocks.TWISTED_PLANKS);
            event.accept(HexcraftBlocks.WITCH_WOOD_PLANKS);
            event.accept(HexcraftBlocks.ECHO_WOOD_PLANKS);
            event.accept(HexcraftItems.EBONY_SIGN);
            event.accept(HexcraftItems.BLOOD_OAK_SIGN);
            event.accept(HexcraftItems.HELL_BARK_SIGN);
            event.accept(HexcraftItems.WHITE_OAK_SIGN);
            event.accept(HexcraftItems.ALDER_SIGN);
            event.accept(HexcraftItems.WITCH_HAZEL_SIGN);
            event.accept(HexcraftItems.WILLOW_SIGN);
            event.accept(HexcraftItems.HAWTHORN_SIGN);
            event.accept(HexcraftItems.CEDAR_SIGN);
            event.accept(HexcraftItems.DISTORTED_SIGN);
            event.accept(HexcraftItems.ELDER_SIGN);
            event.accept(HexcraftItems.JUNIPER_SIGN);
            event.accept(HexcraftItems.ROWAN_SIGN);
            event.accept(HexcraftItems.TWISTED_SIGN);
            event.accept(HexcraftItems.WITCH_WOOD_SIGN);
            event.accept(HexcraftItems.ECHO_WOOD_SIGN);
            event.accept(HexcraftItems.CRATE_EBONY);
            event.accept(HexcraftItems.CRATE_BLOOD_OAK);
            event.accept(HexcraftItems.CRATE_HELLBARK);
            event.accept(HexcraftItems.CRATE_WHITE_OAK);
            event.accept(HexcraftItems.CRATE_ALDER);
            event.accept(HexcraftItems.CRATE_WITCH_HAZEL);
            event.accept(HexcraftItems.CRATE_WILLOW);
            event.accept(HexcraftItems.CRATE_HAWTHORN);
            event.accept(HexcraftItems.CRATE_CEDAR);
            event.accept(HexcraftItems.CRATE_DISTORTED);
            event.accept(HexcraftItems.CRATE_ELDER);
            event.accept(HexcraftItems.CRATE_JUNIPER);
            event.accept(HexcraftItems.CRATE_ROWAN);
            event.accept(HexcraftItems.CRATE_TWISTED);
            event.accept(HexcraftItems.CRATE_WITCH_WOOD);
            event.accept(HexcraftItems.CRATE_ECHO_WOOD);
            event.accept(HexcraftItems.CRATE_OAK);
            event.accept(HexcraftItems.CRATE_SPRUCE);
            event.accept(HexcraftItems.CRATE_BIRCH);
            event.accept(HexcraftItems.CRATE_JUNGLE);
            event.accept(HexcraftItems.CRATE_ACACIA);
            event.accept(HexcraftItems.CRATE_DARK_OAK);
            event.accept(HexcraftItems.CRATE_CRIMSON);
            event.accept(HexcraftItems.CRATE_WARPED);
            event.accept(HexcraftItems.CRATE_MANGROVE);
            event.accept(HexcraftBlocks.EBONY_BOOKSHELF);
            event.accept(HexcraftBlocks.BLOOD_OAK_BOOKSHELF);
            event.accept(HexcraftBlocks.HELL_BARK_BOOKSHELF);
            event.accept(HexcraftBlocks.WHITE_OAK_BOOKSHELF);
            event.accept(HexcraftBlocks.ALDER_BOOKSHELF);
            event.accept(HexcraftBlocks.WITCH_HAZEL_BOOKSHELF);
            event.accept(HexcraftBlocks.WILLOW_BOOKSHELF);
            event.accept(HexcraftBlocks.HAWTHORN_BOOKSHELF);
            event.accept(HexcraftBlocks.CEDAR_BOOKSHELF);
            event.accept(HexcraftBlocks.DISTORTED_BOOKSHELF);
            event.accept(HexcraftBlocks.ELDER_BOOKSHELF);
            event.accept(HexcraftBlocks.JUNIPER_BOOKSHELF);
            event.accept(HexcraftBlocks.ROWAN_BOOKSHELF);
            event.accept(HexcraftBlocks.TWISTED_BOOKSHELF);
            event.accept(HexcraftBlocks.WITCH_WOOD_BOOKSHELF);
            event.accept(HexcraftBlocks.ECHO_WOOD_BOOKSHELF);
            event.accept(HexcraftBlocks.FAIRY_LANTERN);
            event.accept(HexcraftBlocks.PIXIE_LANTERN);
            event.accept(HexcraftBlocks.ECHO_FUNGAL_LAMP);
            event.accept(HexcraftBlocks.HELL_FUNGAL_LAMP);
            event.accept(HexcraftBlocks.ENDER_BRAMBLE);
            event.accept(HexcraftBlocks.WILD_BRAMBLE);
            event.accept(HexcraftBlocks.BLOOD_MUSHROOM_BLOCK);
            event.accept(HexcraftBlocks.BLOOD_MUSHROOM_STEM);
            event.accept(HexcraftBlocks.LIVING_KELP_BLOCK);
            event.accept(HexcraftBlocks.LILITH_TROPHY);

       }
    }

    @Mod.EventBusSubscriber(modid = MOD_ID, bus = Mod.EventBusSubscriber.Bus.MOD)
    public static class ClientModEvents {
        @SubscribeEvent
        public static void onClientSetup(FMLClientSetupEvent event) {
            event.enqueueWork(() -> {
                ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(HexcraftBlocks.BLOODY_ROSE.getId(), HexcraftBlocks.POTTED_BLOODY_ROSE);
                ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(HexcraftBlocks.VAMPIRE_ORCHID.getId(), HexcraftBlocks.POTTED_VAMPIRE_ORCHID);
                //((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(HexcraftBlocks.BLOOD_MUSHROOM.getId(), HexcraftBlocks.POTTED_BLOOD_MUSHROOM);
                ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(HexcraftBlocks.EBONY_SAPLING.getId(), HexcraftBlocks.POTTED_EBONY_SAPLING);
                ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(HexcraftBlocks.BLOOD_OAK_SAPLING.getId(), HexcraftBlocks.POTTED_BLOOD_OAK_SAPLING);
                ((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(HexcraftBlocks.HELL_BARK_SAPLING.getId(), HexcraftBlocks.POTTED_HELL_BARK_SAPLING);
                //((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(HexcraftBlocks.WHITE_OAK_SAPLING.getId(), HexcraftBlocks.POTTED_WHITE_OAK_SAPLING);
                //((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(HexcraftBlocks.ALDER_SAPLING.getId(), HexcraftBlocks.POTTED_ALDER_SAPLING);
                //((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(HexcraftBlocks.WITCH_HAZEL_SAPLING.getId(), HexcraftBlocks.POTTED_WITCH_HAZEL_SAPLING);
                //((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(HexcraftBlocks.WILLOW_SAPLING.getId(), HexcraftBlocks.POTTED_WILLOW_SAPLING);
                //((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(HexcraftBlocks.HAWTHORN_SAPLING.getId(), HexcraftBlocks.POTTED_HAWTHORN_SAPLING);
                //((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(HexcraftBlocks.CEDAR_SAPLING.getId(), HexcraftBlocks.POTTED_CEDAR_SAPLING);
                //((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(HexcraftBlocks.DISTORTED_SAPLING.getId(), HexcraftBlocks.POTTED_DISTORTED_SAPLING);
                //((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(HexcraftBlocks.ELDER_SAPLING.getId(), HexcraftBlocks.POTTED_ELDER_SAPLING);
                //((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(HexcraftBlocks.JUNIPER_SAPLING.getId(), HexcraftBlocks.POTTED_JUNIPER_SAPLING);
                //((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(HexcraftBlocks.ROWAN_SAPLING.getId(), HexcraftBlocks.POTTED_ROWAN_SAPLING);
                //((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(HexcraftBlocks.TWISTED_SAPLING.getId(), HexcraftBlocks.POTTED_TWISTED_SAPLING);
                //((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(HexcraftBlocks.WITCH_WOOD_SAPLING.getId(), HexcraftBlocks.POTTED_WITCH_WOOD_SAPLING);
                //((FlowerPotBlock) Blocks.FLOWER_POT).addPlant(HexcraftBlocks.ECHO_WOOD_SAPLING.getId(), HexcraftBlocks.POTTED_ECHO_WOOD_SAPLING);

                Sheets.addWoodType(HexcraftWoodTypes.EBONY);
                Sheets.addWoodType(HexcraftWoodTypes.BLOOD_OAK);
                Sheets.addWoodType(HexcraftWoodTypes.HELL_BARK);
                Sheets.addWoodType(HexcraftWoodTypes.WHITE_OAK);
                Sheets.addWoodType(HexcraftWoodTypes.ALDER);
                Sheets.addWoodType(HexcraftWoodTypes.WITCH_HAZEL);
                Sheets.addWoodType(HexcraftWoodTypes.WILLOW);
                Sheets.addWoodType(HexcraftWoodTypes.HAWTHORN);
                Sheets.addWoodType(HexcraftWoodTypes.CEDAR);
                Sheets.addWoodType(HexcraftWoodTypes.DISTORTED);
                Sheets.addWoodType(HexcraftWoodTypes.ELDER);
                Sheets.addWoodType(HexcraftWoodTypes.JUNIPER);
                Sheets.addWoodType(HexcraftWoodTypes.ROWAN);
                Sheets.addWoodType(HexcraftWoodTypes.TWISTED);
                Sheets.addWoodType(HexcraftWoodTypes.WITCH_WOOD);
                Sheets.addWoodType(HexcraftWoodTypes.ECHO_WOOD);
            });
        }
    }
}
